# 1. 환경설정

In [5]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import warnings
warnings.filterwarnings('ignore')
import time
import pickle
from tqdm import tqdm

In [6]:
import pickle
with open('sector.pickle','rb') as f:
    sector = pickle.load(f)

# 2. 일별 종가 데이터 수집 - 10개
키움API는 구름IDE에서 실행이 안되어 따로 웹크롤링

In [7]:
def get_stock_price(code, num_of_pages):
    url = f"http://finance.naver.com/item/sise_day.nhn?code={code}" 
    bs = BeautifulSoup(requests.get(url=url, headers = headers).text, 'html.parser')
    pgrr = bs.find("td", class_="pgRR")
    last_page = int(pgrr.a["href"].split('=')[-1])
    pages = min(last_page, num_of_pages) # 마지막 페이지와 가져올 페이지 수 중에 작은 값 선택
    df = pd.DataFrame()

    for page in range(1, pages+1):
        page_url = '{}&page={}'.format(url, page)
        df = df.append(pd.read_html(requests.get(page_url, headers={'User-agent': 'Mozilla/5.0'}).text)[0])
        
    df['일자'] = pd.to_datetime(df['날짜']) 
    df = df.dropna()
    df[['종가',  '시가', '고가', '저가', '거래량']] = df[['종가', '시가', '고가', '저가', '거래량']].astype(int) # int형으로 변경
    df = df[['일자', '거래량','시가', '고가', '저가','종가']] # 컬럼 순서 정렬
    df = df.sort_values(by = '일자') # 날짜순으로 정렬
    df = df.loc[::-1].reset_index(drop=True)
    return df

In [10]:
headers = {'User-agent': 'Mozilla/5.0'}
pages = 20
df_sector_UTD = {}
for sector_name in sector:
    df_sector_UTD[sector_name] = {}

In [11]:
for sector_name, code_list in sector.items():
    for stock_code in tqdm(code_list):
        df_sector_UTD[sector_name][stock_code] = get_stock_price(stock_code,pages)
        time.sleep(0.01)

100%|██████████| 5/5 [00:11<00:00,  2.39s/it]
100%|██████████| 4/4 [00:09<00:00,  2.40s/it]
100%|██████████| 5/5 [00:12<00:00,  2.41s/it]
100%|██████████| 4/4 [00:09<00:00,  2.43s/it]
100%|██████████| 3/3 [00:07<00:00,  2.40s/it]
100%|██████████| 5/5 [00:12<00:00,  2.58s/it]
100%|██████████| 4/4 [00:09<00:00,  2.50s/it]
100%|██████████| 4/4 [00:09<00:00,  2.43s/it]
100%|██████████| 4/4 [00:09<00:00,  2.47s/it]
100%|██████████| 5/5 [00:12<00:00,  2.40s/it]
100%|██████████| 5/5 [00:12<00:00,  2.50s/it]
100%|██████████| 3/3 [00:07<00:00,  2.50s/it]
100%|██████████| 3/3 [00:07<00:00,  2.43s/it]
100%|██████████| 3/3 [00:07<00:00,  2.37s/it]
100%|██████████| 4/4 [00:09<00:00,  2.45s/it]
100%|██████████| 4/4 [00:09<00:00,  2.43s/it]
100%|██████████| 4/4 [00:09<00:00,  2.40s/it]
100%|██████████| 5/5 [00:12<00:00,  2.42s/it]

# 이전 data와 최신 data 병합(최신화)

In [12]:
with open('df_sector_UTD.pickle','rb') as f:
    df_sector = pickle.load(f)

In [13]:
df_sector

{'Food': {'097950':              일자    거래량      시가      고가      저가      종가
  2999 2010-06-08  50727  211000  213500  209500  211000
  2998 2010-06-09  52375  212000  218000  210500  214000
  2997 2010-06-10  61195  214500  219500  213500  219000
  2996 2010-06-11  89684  217000  220000  211500  214500
  2995 2010-06-14  41941  216000  220000  215500  219000
  ...         ...    ...     ...     ...     ...     ...
  4    2022-07-27  16778  396500  400000  394000  395000
  3    2022-07-28  25944  395500  398000  391000  395000
  2    2022-07-29  27618  397500  397500  389000  391500
  1    2022-08-01  37653  391500  392000  383500  387000
  0    2022-08-02  29305  387000  388000  383000  385500

  [3000 rows x 6 columns],
  '271560':              일자      거래량      시가      고가      저가      종가
  1246 2017-07-07  1619864   87100   89700   75700   82300
  1245 2017-07-10   840451   82300   88000   81000   88000
  1244 2017-07-11   422303   88000   88000   82700   82800
  1243 2017-07-12   238407   83700   84600   80000   83500
  1242 2017-07-13   218138   83400   84000   80800   81600
  ...         ...      ...     ...     ...     ...     ...
  4    2022-07-27    78702  103000  103500  101000  102000
  3    2022-07-28   122707  102500  103500   99800  100500
  2    2022-07-29    92322  101000  101500   99600  100500
  1    2022-08-01   179252  100000  100500   97000   97800
  0    2022-08-02    89396   97900   99900   97800   99300

  [1247 rows x 6 columns],
  '000080':              일자     거래량     시가     고가     저가     종가
  2999 2010-06-08   41464  32150  32850  32150  32600
  2998 2010-06-09   38492  32650  32800  32450  32500
  2997 2010-06-10   65568  32550  32900  32400  32700
  2996 2010-06-11   71145  32900  33800  32700  33800
  2995 2010-06-14   63202  33800  34300  33400  34150
  ...         ...     ...    ...    ...    ...    ...
  4    2022-07-27  175569  30100  30200  29750  30200
  3    2022-07-28  175955  30350  30550  29900  30150
  2    2022-07-29  269130  30200  30250  29950  30250
  1    2022-08-01  214785  30300  30450  30000  30150
  0    2022-08-02  342932  30200  30750  30100  30700

  [3000 rows x 6 columns],
  '004370':              일자    거래량      시가      고가      저가      종가
  2999 2010-06-08  13195  227000  227000  220000  222000
  2998 2010-06-09   9505  222500  222500  220500  222000
  2997 2010-06-10  14592  222000  227000  221000  224500
  2996 2010-06-11   6006  225000  228000  225000  227000
  2995 2010-06-14   8065  227000  229000  225000  226500
  ...         ...    ...     ...     ...     ...     ...
  4    2022-07-27   8545  282000  283000  280500  281500
  3    2022-07-28  10126  282000  284000  278000  278500
  2    2022-07-29  21450  280500  280500  276000  279500
  1    2022-08-01  32610  277500  278000  272000  273500
  0    2022-08-02  28311  271500  281500  271500  281000

  [3000 rows x 6 columns],
  '005300':              일자     거래량      시가      고가      저가      종가
  2999 2010-06-08   17720   78300   78300   77300   78200
  2998 2010-06-09   21610   77700   78200   77000   77600
  2997 2010-06-10   25830   77900   78000   76800   76800
  2996 2010-06-11   17700   77400   77800   76800   77600
  2995 2010-06-14   26280   77700   79200   77700   78600
  ...         ...     ...     ...     ...     ...     ...
  4    2022-07-27   17714  174500  177500  171500  172500
  3    2022-07-28   15095  174000  175500  171500  173000
  2    2022-07-29   26679  175500  180000  173000  177500
  1    2022-08-01  170694  178000  184500  166000  168000
  0    2022-08-02   75189  168500  171000  167000  170000

  [3000 rows x 6 columns]},
 'Clothing': {'093050':              일자     거래량     시가     고가     저가     종가
  2999 2010-06-08  166089  24850  25650  24850  25550
  2998 2010-06-09  208765  25550  26500  25350  26450
  2997 2010-06-10  237507  26750  27350  26500  27050
  2996 2010-06-11  175558  27050  27500  26600  26750
  2995 2010-06-14  137210  26600  27550  26600  27400
  ...         ...     ...    ...    ...    ...    ...
  4    2022-07-27   16930  17100  17100  16800  17000
  3    2022-07-28   35965  17000  17600  16900  17500
  2    2022-07-29   30425  17500  17650  17100  17450
  1    2022-08-01   30562  17400  17450  16950  17050
  0    2022-08-02   31910  17050  17100  16800  16900

  [3000 rows x 6 columns],
  '020000':              일자     거래량     시가     고가     저가     종가
  2999 2010-06-08  136130  13350  13750  13350  13750
  2998 2010-06-09  104960  13750  14350  13650  14000
  2997 2010-06-10  126502  14050  14300  13950  14000
  2996 2010-06-11   69514  14100  14350  14000  14200
  2995 2010-06-14  101678  14250  14400  13950  14100
  ...         ...     ...    ...    ...    ...    ...
  4    2022-07-27   51262  30600  30950  30000  30800
  3    2022-07-28   57077  31050  31200  30100  30350
  2    2022-07-29   52004  30750  31200  30550  31100
  1    2022-08-01   31876  30900  31250  30750  30950
  0    2022-08-02   44372  30900  30950  30250  30600

  [3000 rows x 6 columns],
  '105630':              일자     거래량     시가     고가     저가     종가
  2999 2010-06-08   48616   5524   5727   5524   5682
  2998 2010-06-09   25585   5675   5735   5592   5697
  2997 2010-06-10   60671   5630   5697   5584   5630
  2996 2010-06-11   19298   5690   5690   5532   5622
  2995 2010-06-14   50937   5667   5705   5554   5569
  ...         ...     ...    ...    ...    ...    ...
  4    2022-07-27  195686  16400  16650  16200  16600
  3    2022-07-28  299343  16800  16950  16200  16250
  2    2022-07-29  310992  16400  16750  16350  16750
  1    2022-08-01  257533  16850  16900  16600  16700
  0    2022-08-02  328300  16650  16800  16100  16300

  [3000 rows x 6 columns],
  '001070':              일자     거래량     시가     고가     저가     종가
  2999 2010-06-08    9655   5340   5500   5240   5470
  2998 2010-06-09    3100   5520   5520   5340   5450
  2997 2010-06-10   13150   5400   5400   5220   5280
  2996 2010-06-11    8840   5360   5740   5320   5740
  2995 2010-06-14    1400   5890   5890   5680   5720
  ...         ...     ...    ...    ...    ...    ...
  4    2022-07-27    3484  50300  50500  49900  50200
  3    2022-07-28  230822  50100  50100  47800  48000
  2    2022-07-29   13648  48000  49450  48000  49000
  1    2022-08-01   18755  48500  49950  48400  49950
  0    2022-08-02    3583  49950  50900  49700  50900

  [3000 rows x 6 columns]},
 'Chemical': {'051910':              일자     거래량      시가      고가      저가      종가
  2999 2010-06-08  254900  286500  291000  285000  288000
  2998 2010-06-09  251091  290000  290000  285000  289000
  2997 2010-06-10  270990  289000  290500  283000  290000
  2996 2010-06-11  241134  294000  294000  285500  290500
  2995 2010-06-14  228545  290500  292000  286500  290000
  ...         ...     ...     ...     ...     ...     ...
  4    2022-07-27  417385  584000  587000  556000  565000
  3    2022-07-28  553103  572000  605000  555000  598000
  2    2022-07-29  323842  603000  605000  595000  603000
  1    2022-08-01  281615  608000  628000  601000  613000
  0    2022-08-02  162952  612000  613000  604000  610000

  [3000 rows x 6 columns],
  '096770':              일자     거래량      시가      고가      저가      종가
  2999 2010-06-08  403667  105500  106500  104500  105000
  2998 2010-06-09  370062  105000  108000  105000  105500
  2997 2010-06-10  609909  107500  109000  106500  106500
  2996 2010-06-11  339220  109500  110000  107000  108500
  2995 2010-06-14  283633  110000  110500  108500  109000
  ...         ...     ...     ...     ...     ...     ...
  4    2022-07-27  179267  184000  184500  180000  182500
  3    2022-07-28  326105  185000  187500  178500  182000
  2    2022-07-29  688623  183000  191000  182500  187500
  1    2022-08-01  265180  188500  190500  185500  186000
  0    2022-08-02  355370  186000  186500  179500  180000

  [3000 rows x 6 columns],
  '010950':              일자     거래량     시가     고가     저가     종가
  2999 2010-06-08  210874  51000  51700  50800  51200
  2998 2010-06-09  391071  51200  51300  50100  50500
  2997 2010-06-10  364663  50600  50900  50100  50200
  2996 2010-06-11  420603  50800  51500  50700  51100
  2995 2010-06-14  257125  51200  52000  51200  51800
  ...         ...     ...    ...    ...    ...    ...
  4    2022-07-27  215846  91300  93000  91300  93000
  3    2022-07-28  538463  93600  93800  90500  91300
  2    2022-07-29  373846  91800  93000  91000  91800
  1    2022-08-01  391034  93200  94200  91900  91900
  0    2022-08-02  590070  92400  92400  88400  88600

  [3000 rows x 6 columns],
  '051900':              일자     거래량      시가      고가      저가      종가
  2999 2010-06-08   24792  335000  339000  332500  335500
  2998 2010-06-09   25404  333500  337500  330500  336000
  2997 2010-06-10   55959  335000  337000  329500  335000
  2996 2010-06-11   93322  333000  334000  321000  330500
  2995 2010-06-14   21964  330500  341000  329500  337000
  ...         ...     ...     ...     ...     ...     ...
  4    2022-07-27  167418  722000  765000  700000  752000
  3    2022-07-28  145657  752000  779000  726000  743000
  2    2022-07-29  115281  765000  791000  760000  779000
  1    2022-08-01   55718  784000  792000  774000  788000
  0    2022-08-02   37017  789000  790000  767000  767000

  [3000 rows x 6 columns],
  '090430':              일자     거래량      시가      고가      저가      종가
  2999 2010-06-08  133070   97300   97500   96000   97300
  2998 2010-06-09  101080   98000   99000   97300   98700
  2997 2010-06-10  302410   98800  100000   97100   98300
  2996 2010-06-11  199700   99600  100100   97700   98000
  2995 2010-06-14  163080   98000  100300   98000   98200
  ...         ...     ...     ...     ...     ...     ...
  4    2022-07-27  229211  137500  142500  134000  141500
  3    2022-07-28  858036  141000  144000  127000  127500
  2    2022-07-29  527143  128500  129000  125500  129000
  1    2022-08-01  168532  129000  129000  127500  128000
  0    2022-08-02  141412  127500  128000  126000  127000

  [3000 rows x 6 columns]},
 'Medicine': {'207940':              일자      거래량      시가      고가      저가      종가
  1408 2016-11-10  7264007  133421  146268  124032  142315
  1407 2016-11-11  8236911  147751  184318  140339  159610
  1406 2016-11-14  3012422  163070  175423  163070  173447
  1405 2016-11-15  2623646  176906  179376  160599  164058
  1404 2016-11-16  1680639  166529  170976  161587  168011
  ...         ...      ...     ...     ...     ...     ...
  4    2022-07-27    84428  829000  847000  828000  841000
  3    2022-07-28   108584  844000  867000  844000  863000
  2    2022-07-29    62152  868000  875000  862000  865000
  1    2022-08-01    63497  857000  879000  856000  878000
  0    2022-08-02    54952  882000  883000  860000  866000

  [1409 rows x 6 columns],
  '068270':              일자      거래량      시가      고가      저가      종가
  2999 2010-06-08  1383178   17328   17905   17194   17728
  2998 2010-06-09   909685   17772   18083   17461   17994
  2997 2010-06-10   842885   18261   18305   18039   18216
  2996 2010-06-11  1266465   18572   18838   18261   18483
  2995 2010-06-14  1361897   18616   18883   18350   18705
  ...         ...      ...     ...     ...     ...     ...
  4    2022-07-27   356411  186000  191000  186000  189500
  3    2022-07-28   349970  191000  191500  189000  190000
  2    2022-07-29   282424  192000  192500  188500  190000
  1    2022-08-01   241140  190500  190500  186000  187500
  0    2022-08-02   244365  188000  190000  185500  186000

  [3000 rows x 6 columns],
  '000100':              일자     거래량     시가     고가     저가     종가
  2999 2010-06-08  252801  22433  23389  22212  23389
  2998 2010-06-09  156377  23389  23389  22874  23315
  2997 2010-06-10  454031  23389  23536  22948  23536
  2996 2010-06-11  367464  23389  23610  22653  23095
  2995 2010-06-14  321196  22948  23389  22653  22727
  ...         ...     ...    ...    ...    ...    ...
  4    2022-07-27  140105  58100  58100  57500  58000
  3    2022-07-28  130141  57600  58300  57600  57800
  2    2022-07-29  170417  58000  58300  57500  57800
  1    2022-08-01  162282  57700  57700  56800  57200
  0    2022-08-02  117339  56900  57200  56500  56700

  [3000 rows x 6 columns],
  '128940':              일자     거래량      시가      고가      저가      종가
  2961 2010-07-30  383395   57942   66633   57942   64316
  2960 2010-08-02  159281   63414   63672   58264   58586
  2959 2010-08-03   57060   58715   59873   58586   58715
  2958 2010-08-04   99727   58715   60002   55367   58715
  2957 2010-08-05  114537   59552   59552   56268   56654
  ...         ...     ...     ...     ...     ...     ...
  4    2022-07-27   19062  307000  311000  306000  309000
  3    2022-07-28   16656  308500  311500  308500  309000
  2    2022-07-29   17174  311500  314500  308000  309500
  1    2022-08-01   17830  307000  312500  306000  307500
  0    2022-08-02   19510  309000  309500  303500  304500

  [2962 rows x 6 columns]},
 'Non_Metal': {'003670':              일자      거래량      시가      고가      저가      종가
  2999 2010-06-08    43936    7097    7135    6937    7078
  2998 2010-06-09    53468    7078    7106    6900    6956
  2997 2010-06-10    54074    7041    7050    6956    6956
  2996 2010-06-11    77606    7031    7088    6871    6956
  2995 2010-06-14    48128    7050    7050    6787    6862
  ...         ...      ...     ...     ...     ...     ...
  4    2022-07-27   351428  118500  119000  114500  116000
  3    2022-07-28  4407062  118500  139000  117500  135500
  2    2022-07-29   979328  135000  136500  130500  131500
  1    2022-08-01   649284  132500  135000  131500  133500
  0    2022-08-02   440347  134500  136000  131500  133500

  [3000 rows x 6 columns],
  '003410':              일자      거래량    시가    고가    저가    종가
  2999 2010-06-08   313987  1159  1164  1133  1159
  2998 2010-06-09   333429  1159  1159  1131  1138
  2997 2010-06-10  1011509  1133  1133  1094  1094
  2996 2010-06-11   786857  1112  1118  1092  1094
  2995 2010-06-14   643862  1105  1140  1099  1127
  ...         ...      ...   ...   ...   ...   ...
  4    2022-07-27  1004403  6480  6770  6480  6730
  3    2022-07-28   471634  6730  6750  6580  6600
  2    2022-07-29   381918  6610  6700  6610  6670
  1    2022-08-01   335437  6700  6770  6670  6770
  0    2022-08-02   306086  6770  6800  6680  6750

  [3000 rows x 6 columns],
  '010780':              일자     거래량     시가     고가     저가     종가
  2999 2010-06-08   54032   5859   6191   5859   6153
  2998 2010-06-09  109726   6217   6396   6185   6319
  2997 2010-06-10  119332   6249   6908   6249   6844
  2996 2010-06-11  101470   7004   7355   6588   6844
  2995 2010-06-14   45652   7036   7036   6588   6620
  ...         ...     ...    ...    ...    ...    ...
  4    2022-07-27   28466  40850  40950  40200  40450
  3    2022-07-28   41139  41000  41200  40250  40350
  2    2022-07-29   60010  40350  41050  40200  40300
  1    2022-08-01   28527  40200  40800  40150  40700
  0    2022-08-02   29355  40400  41000  40250  40400

  [3000 rows x 6 columns]},
 'Metal': {'005490':              일자     거래량      시가      고가      저가      종가
  2999 2010-06-08  168069  447000  453000  442500  450000
  2998 2010-06-09  269627  446000  452000  443000  447000
  2997 2010-06-10  284195  450000  455000  445000  448500
  2996 2010-06-11  341722  457500  466000  457000  465500
  2995 2010-06-14  338840  474000  478500  470000  473000
  ...         ...     ...     ...     ...     ...     ...
  4    2022-07-27  185386  235500  237000  234000  236500
  3    2022-07-28  179304  238500  239500  237000  238500
  2    2022-07-29  306236  237500  243000  237500  242000
  1    2022-08-01  273551  245000  245000  238500  240000
  0    2022-08-02  277704  240000  240500  234500  236000

  [3000 rows x 6 columns],
  '010130':              일자     거래량      시가      고가      저가      종가
  2999 2010-06-08  150151  183000  187000  180000  183500
  2998 2010-06-09  188979  187500  193000  186000  191000
  2997 2010-06-10  150810  193000  198000  191500  198000
  2996 2010-06-11   89388  198000  200500  195500  199500
  2995 2010-06-14   85989  198000  205000  197000  203000
  ...         ...     ...     ...     ...     ...     ...
  4    2022-07-27   29138  471000  473500  462500  467000
  3    2022-07-28   29431  469500  474000  467500  472500
  2    2022-07-29   41110  479500  483500  476000  477500
  1    2022-08-01   65539  477000  493500  476500  487000
  0    2022-08-02   27854  480000  483000  475500  479500

  [3000 rows x 6 columns],
  '004020':              일자     거래량     시가     고가     저가     종가
  2999 2010-06-08  591502  82800  84300  82400  83000
  2998 2010-06-09  694504  83800  85600  83100  85300
  2997 2010-06-10  405120  85500  86800  84400  86500
  2996 2010-06-11  499714  87500  87900  86700  87200
  2995 2010-06-14  470386  87000  88800  87000  87800
  ...         ...     ...    ...    ...    ...    ...
  4    2022-07-27  575118  33700  33800  32700  33150
  3    2022-07-28  391688  33350  33550  33100  33350
  2    2022-07-29  618135  33450  34100  33350  34100
  1    2022-08-01  423635  34200  34400  33550  33900
  0    2022-08-02  353866  33950  34100  33000  33150

  [3000 rows x 6 columns],
  '016380':              일자      거래량      시가      고가      저가      종가
  2999 2010-06-08     2938  480258  491998  476523  491998
  2998 2010-06-09     2197  494132  494132  482926  483460
  2997 2010-06-10     2694  483993  498401  483993  493599
  2996 2010-06-11     5667  501603  514943  498935  510674
  2995 2010-06-14     7293  515477  533620  513876  532553
  ...         ...      ...     ...     ...     ...     ...
  4    2022-07-27   488270   12200   12300   11900   12000
  3    2022-07-28  1850246   12150   12750   12050   12100
  2    2022-07-29   467832   12200   12450   12100   12250
  1    2022-08-01   657551   12350   12750   12300   12550
  0    2022-08-02   521322   12600   12700   12150   12250

  [3000 rows x 6 columns],
  '001230':              일자     거래량     시가     고가     저가     종가
  2999 2010-06-08  204919  18066  18382  17840  18382
  2998 2010-06-09  211957  18382  18518  18111  18201
  2997 2010-06-10  299575  18292  18969  18247  18653
  2996 2010-06-11  241281  18924  19240  18924  19060
  2995 2010-06-14  266388  19285  19692  19240  19556
  ...         ...     ...    ...    ...    ...    ...
  4    2022-07-27  250673  12700  12700  12450  12550
  3    2022-07-28  268443  12700  12850  12550  12650
  2    2022-07-29  686362  12750  13300  12700  13250
  1    2022-08-01  419680  13400  13450  13050  13100
  0    2022-08-02  513049  13100  13150  12550  12700

  [3000 rows x 6 columns]},
 'Machine': {'034020':              일자      거래량     시가     고가     저가     종가
  2999 2010-06-08   733424  53244  54009  52709  53780
  2998 2010-06-09  1401169  53780  56228  53015  53627
  2997 2010-06-10   611957  54392  55233  54162  54468
  2996 2010-06-11   602592  55463  55463  54545  54927
  2995 2010-06-14   552733  55310  55845  54851  55310
  ...         ...      ...    ...    ...    ...    ...
  4    2022-07-27  1948230  17750  17950  17600  17900
  3    2022-07-28  3017942  18200  18200  17800  18150
  2    2022-07-29  6072369  18200  19000  18100  18750
  1    2022-08-01  3055710  18800  18950  18500  18750
  0    2022-08-02  4310639  18800  19200  18300  18450

  [3000 rows x 6 columns],
  '018880':              일자      거래량     시가     고가     저가     종가
  2999 2010-06-08  1276965   3000   3090   2970   3050
  2998 2010-06-09  1323250   3070   3090   3010   3080
  2997 2010-06-10  2192070   3080   3130   2990   3050
  2996 2010-06-11   833625   3100   3100   3020   3020
  2995 2010-06-14  1119085   3040   3170   3040   3140
  ...         ...      ...    ...    ...    ...    ...
  4    2022-07-27   349952  10550  10550  10300  10450
  3    2022-07-28   368980  10450  10600  10350  10450
  2    2022-07-29   744701  10500  10800  10500  10650
  1    2022-08-01   431680  10500  10800  10400  10700

In [14]:
for sector_name, df_dict in df_sector.items():
    for stock_code, df in df_dict.items():
        df = pd.concat([df_sector_UTD[sector_name][stock_code],df_sector[sector_name][stock_code]],axis=0)
        df=df.drop_duplicates(subset=['일자'])
        df = df.sort_values(by=df.columns[0],ascending=True)
        df = df.reset_index(drop=True)
        df_sector_UTD[sector_name][stock_code] = df

In [15]:
df_sector_UTD['Food']['097950']

             일자    거래량      시가      고가      저가      종가
0    2010-06-08  50727  211000  213500  209500  211000
1    2010-06-09  52375  212000  218000  210500  214000
2    2010-06-10  61195  214500  219500  213500  219000
3    2010-06-11  89684  217000  220000  211500  214500
4    2010-06-14  41941  216000  220000  215500  219000
...         ...    ...     ...     ...     ...     ...
3005 2022-08-10  66726  426500  428500  414500  423500
3006 2022-08-11  66420  425000  425000  417000  421500
3007 2022-08-12  43606  419000  422000  414000  416500
3008 2022-08-16  31340  418000  420500  416500  418500
3009 2022-08-17  30523  419500  423000  413500  417000

[3010 rows x 6 columns]

In [16]:
df_sector_UTD

{'Food': {'097950':              일자    거래량      시가      고가      저가      종가
  0    2010-06-08  50727  211000  213500  209500  211000
  1    2010-06-09  52375  212000  218000  210500  214000
  2    2010-06-10  61195  214500  219500  213500  219000
  3    2010-06-11  89684  217000  220000  211500  214500
  4    2010-06-14  41941  216000  220000  215500  219000
  ...         ...    ...     ...     ...     ...     ...
  3005 2022-08-10  66726  426500  428500  414500  423500
  3006 2022-08-11  66420  425000  425000  417000  421500
  3007 2022-08-12  43606  419000  422000  414000  416500
  3008 2022-08-16  31340  418000  420500  416500  418500
  3009 2022-08-17  30523  419500  423000  413500  417000

  [3010 rows x 6 columns],
  '271560':              일자      거래량      시가      고가      저가      종가
  0    2017-07-07  1619864   87100   89700   75700   82300
  1    2017-07-10   840451   82300   88000   81000   88000
  2    2017-07-11   422303   88000   88000   82700   82800
  3    2017-07-12   238407   83700   84600   80000   83500
  4    2017-07-13   218138   83400   84000   80800   81600
  ...         ...      ...     ...     ...     ...     ...
  1252 2022-08-10   151113  106500  109500  105500  106500
  1253 2022-08-11   107924  106500  107500  105000  106000
  1254 2022-08-12    68543  105500  107000  103000  104500
  1255 2022-08-16    83431  105000  107000  103500  105500
  1256 2022-08-17   123633  105500  109000  105000  106000

  [1257 rows x 6 columns],
  '000080':              일자     거래량     시가     고가     저가     종가
  0    2010-06-08   41464  32150  32850  32150  32600
  1    2010-06-09   38492  32650  32800  32450  32500
  2    2010-06-10   65568  32550  32900  32400  32700
  3    2010-06-11   71145  32900  33800  32700  33800
  4    2010-06-14   63202  33800  34300  33400  34150
  ...         ...     ...    ...    ...    ...    ...
  3005 2022-08-10  134134  31450  31450  31050  31250
  3006 2022-08-11  276818  31500  31750  31250  31700
  3007 2022-08-12  395389  31600  32700  31600  32550
  3008 2022-08-16  622536  32600  32600  31050  31050
  3009 2022-08-17  484660  31100  31150  30150  30400

  [3010 rows x 6 columns],
  '004370':              일자    거래량      시가      고가      저가      종가
  0    2010-06-08  13195  227000  227000  220000  222000
  1    2010-06-09   9505  222500  222500  220500  222000
  2    2010-06-10  14592  222000  227000  221000  224500
  3    2010-06-11   6006  225000  228000  225000  227000
  4    2010-06-14   8065  227000  229000  225000  226500
  ...         ...    ...     ...     ...     ...     ...
  3005 2022-08-10  25550  300000  304500  295000  297000
  3006 2022-08-11  15952  298000  299500  293500  298000
  3007 2022-08-12  14871  297000  298000  291000  294000
  3008 2022-08-16  33303  295500  302500  294000  299500
  3009 2022-08-17  55385  299500  299500  283000  290500

  [3010 rows x 6 columns],
  '005300':              일자    거래량      시가      고가      저가      종가
  0    2010-06-08  17720   78300   78300   77300   78200
  1    2010-06-09  21610   77700   78200   77000   77600
  2    2010-06-10  25830   77900   78000   76800   76800
  3    2010-06-11  17700   77400   77800   76800   77600
  4    2010-06-14  26280   77700   79200   77700   78600
  ...         ...    ...     ...     ...     ...     ...
  3005 2022-08-10  24935  169000  169500  165000  165500
  3006 2022-08-11  29737  165500  167000  165000  166500
  3007 2022-08-12  21932  167000  167000  165000  166000
  3008 2022-08-16  51184  166500  167000  161500  162500
  3009 2022-08-17  77235  163000  163000  156500  160000

  [3010 rows x 6 columns]},
 'Clothing': {'093050':              일자     거래량     시가     고가     저가     종가
  0    2010-06-08  166089  24850  25650  24850  25550
  1    2010-06-09  208765  25550  26500  25350  26450
  2    2010-06-10  237507  26750  27350  26500  27050
  3    2010-06-11  175558  27050  27500  26600  26750
  4    2010-06-14  137210  26600  27550  26600  27400
  ...         ...     ...    ...    ...    ...    ...
  3005 2022-08-10   30268  17350  17400  16850  16900
  3006 2022-08-11   55248  16950  17200  16900  17050
  3007 2022-08-12   28386  17050  17550  16900  17500
  3008 2022-08-16   34585  17500  17700  17400  17600
  3009 2022-08-17   52302  17600  17700  17050  17400

  [3010 rows x 6 columns],
  '020000':              일자     거래량     시가     고가     저가     종가
  0    2010-06-08  136130  13350  13750  13350  13750
  1    2010-06-09  104960  13750  14350  13650  14000
  2    2010-06-10  126502  14050  14300  13950  14000
  3    2010-06-11   69514  14100  14350  14000  14200
  4    2010-06-14  101678  14250  14400  13950  14100
  ...         ...     ...    ...    ...    ...    ...
  3005 2022-08-10  287769  29100  29850  28400  29100
  3006 2022-08-11   93041  29400  29600  29050  29450
  3007 2022-08-12   62351  29400  29750  29150  29750
  3008 2022-08-16   64082  29950  29950  29250  29450
  3009 2022-08-17   76362  29600  29950  29150  29250

  [3010 rows x 6 columns],
  '105630':              일자      거래량     시가     고가     저가     종가
  0    2010-06-08    48616   5524   5727   5524   5682
  1    2010-06-09    25585   5675   5735   5592   5697
  2    2010-06-10    60671   5630   5697   5584   5630
  3    2010-06-11    19298   5690   5690   5532   5622
  4    2010-06-14    50937   5667   5705   5554   5569
  ...         ...      ...    ...    ...    ...    ...
  3005 2022-08-10   480664  17800  17900  16850  16950
  3006 2022-08-11   276569  17300  17350  17050  17150
  3007 2022-08-12   438568  17150  17900  17150  17550
  3008 2022-08-16   538455  17800  17850  17000  17250
  3009 2022-08-17  1603257  17500  18950  17500  18100

  [3010 rows x 6 columns],
  '001070':              일자    거래량     시가     고가     저가     종가
  0    2010-06-08   9655   5340   5500   5240   5470
  1    2010-06-09   3100   5520   5520   5340   5450
  2    2010-06-10  13150   5400   5400   5220   5280
  3    2010-06-11   8840   5360   5740   5320   5740
  4    2010-06-14   1400   5890   5890   5680   5720
  ...         ...    ...    ...    ...    ...    ...
  3005 2022-08-10    467  51700  52700  51700  52100
  3006 2022-08-11    857  51700  52700  51300  51900
  3007 2022-08-12   2158  51400  52100  51200  51200
  3008 2022-08-16   1424  50800  51500  50700  51400
  3009 2022-08-17    192  51800  51800  51000  51600

  [3010 rows x 6 columns]},
 'Chemical': {'051910':              일자     거래량      시가      고가      저가      종가
  0    2010-06-08  254900  286500  291000  285000  288000
  1    2010-06-09  251091  290000  290000  285000  289000
  2    2010-06-10  270990  289000  290500  283000  290000
  3    2010-06-11  241134  294000  294000  285500  290500
  4    2010-06-14  228545  290500  292000  286500  290000
  ...         ...     ...     ...     ...     ...     ...
  3005 2022-08-10  219243  671000  672000  646000  648000
  3006 2022-08-11  241071  655000  679000  649000  658000
  3007 2022-08-12  181272  653000  665000  645000  665000
  3008 2022-08-16  144859  675000  676000  659000  662000
  3009 2022-08-17  156614  666000  673000  648000  658000

  [3010 rows x 6 columns],
  '096770':              일자     거래량      시가      고가      저가      종가
  0    2010-06-08  403667  105500  106500  104500  105000
  1    2010-06-09  370062  105000  108000  105000  105500
  2    2010-06-10  609909  107500  109000  106500  106500
  3    2010-06-11  339220  109500  110000  107000  108500
  4    2010-06-14  283633  110000  110500  108500  109000
  ...         ...     ...     ...     ...     ...     ...
  3005 2022-08-10  237732  195000  196000  190500  191000
  3006 2022-08-11  378531  195000  199500  193500  198500
  3007 2022-08-12  340241  198500  204500  196000  199500
  3008 2022-08-16  614263  200500  211500  198000  203500
  3009 2022-08-17  597283  205500  213500  205500  210000

  [3010 rows x 6 columns],
  '010950':              일자      거래량     시가     고가     저가     종가
  0    2010-06-08   210874  51000  51700  50800  51200
  1    2010-06-09   391071  51200  51300  50100  50500
  2    2010-06-10   364663  50600  50900  50100  50200
  3    2010-06-11   420603  50800  51500  50700  51100
  4    2010-06-14   257125  51200  52000  51200  51800
  ...         ...      ...    ...    ...    ...    ...
  3005 2022-08-10   326719  87100  88300  86800  86800
  3006 2022-08-11   627788  86800  87600  85900  87100
  3007 2022-08-12  1022910  88100  90700  88100  90100
  3008 2022-08-16   545953  88600  89900  87900  89600
  3009 2022-08-17   441243  89800  91400  89500  91300

  [3010 rows x 6 columns],
  '051900':              일자    거래량      시가      고가      저가      종가
  0    2010-06-08  24792  335000  339000  332500  335500
  1    2010-06-09  25404  333500  337500  330500  336000
  2    2010-06-10  55959  335000  337000  329500  335000
  3    2010-06-11  93322  333000  334000  321000  330500
  4    2010-06-14  21964  330500  341000  329500  337000
  ...         ...    ...     ...     ...     ...     ...
  3005 2022-08-10  26570  744000  748000  732000  736000
  3006 2022-08-11  38683  745000  748000  732000  733000
  3007 2022-08-12  36327  734000  745000  727000  732000
  3008 2022-08-16  28191  734000  736000  715000  732000
  3009 2022-08-17  25024  734000  739000  726000  726000

  [3010 rows x 6 columns],
  '090430':              일자     거래량      시가      고가      저가      종가
  0    2010-06-08  133070   97300   97500   96000   97300
  1    2010-06-09  101080   98000   99000   97300   98700
  2    2010-06-10  302410   98800  100000   97100   98300
  3    2010-06-11  199700   99600  100100   97700   98000
  4    2010-06-14  163080   98000  100300   98000   98200
  ...         ...     ...     ...     ...     ...     ...
  3005 2022-08-10  158237  124500  126500  124000  125000
  3006 2022-08-11  241603  126500  127500  125500  127500
  3007 2022-08-12  122696  126500  128000  126000  126500
  3008 2022-08-16  124587  126500  128000  125500  128000
  3009 2022-08-17  195173  128000  130000  128000  128000

  [3010 rows x 6 columns]},
 'Medicine': {'207940':              일자      거래량      시가      고가      저가      종가
  0    2016-11-10  7264007  133421  146268  124032  142315
  1    2016-11-11  8236911  147751  184318  140339  159610
  2    2016-11-14  3012422  163070  175423  163070  173447
  3    2016-11-15  2623646  176906  179376  160599  164058
  4    2016-11-16  1680639  166529  170976  161587  168011
  ...         ...      ...     ...     ...     ...     ...
  1414 2022-08-10    43858  904000  910000  880000  892000
  1415 2022-08-11    71857  897000  905000  897000  904000
  1416 2022-08-12    39544  905000  910000  890000  910000
  1417 2022-08-16    37178  918000  922000  898000  905000
  1418 2022-08-17    84876  907000  909000  870000  871000

  [1419 rows x 6 columns],
  '068270':              일자      거래량      시가      고가      저가      종가
  0    2010-06-08  1383178   17328   17905   17194   17728
  1    2010-06-09   909685   17772   18083   17461   17994
  2    2010-06-10   842885   18261   18305   18039   18216
  3    2010-06-11  1266465   18572   18838   18261   18483
  4    2010-06-14  1361897   18616   18883   18350   18705
  ...         ...      ...     ...     ...     ...     ...
  3005 2022-08-10   595536  212000  214000  209000  211500
  3006 2022-08-11   500920  213500  215000  209500  212500
  3007 2022-08-12   432947  212000  213500  205500  208000
  3008 2022-08-16   341387  209000  212500  207500  211000
  3009 2022-08-17   328715  211000  214000  210000  212000

  [3010 rows x 6 columns],
  '000100':              일자     거래량     시가     고가     저가     종가
  0    2010-06-08  252801  22433  23389  22212  23389
  1    2010-06-09  156377  23389  23389  22874  23315
  2    2010-06-10  454031  23389  23536  22948  23536
  3    2010-06-11  367464  23389  23610  22653  23095
  4    2010-06-14  321196  22948  23389  22653  22727
  ...         ...     ...    ...    ...    ...    ...
  3005 2022-08-10   98156  58900  59300  58300  58900
  3006 2022-08-11  130330  59200  59300  58500  59000
  3007 2022-08-12  100918  59000  59500  58500  58700
  3008 2022-08-16  178679  58700  58800  57800  58000
  3009 2022-08-17  141603  58400  58500  57000  57500

  [3010 rows x 6 columns],
  '128940':              일자     거래량      시가      고가      저가      종가
  0    2010-07-30  383395   57942   66633   57942   64316
  1    2010-08-02  159281   63414   63672   58264   58586
  2    2010-08-03   57060   58715   59873   58586   58715
  3    2010-08-04   99727   58715   60002   55367   58715
  4    2010-08-05  114537   59552   59552   56268   56654
  ...         ...     ...     ...     ...     ...     ...
  2967 2022-08-10   24678  324000  328500  319000  321000
  2968 2022-08-11   30208  320000  323500  316000  317500
  2969 2022-08-12   22473  317000  320000  313000  317000
  2970 2022-08-16   19390  317000  318500  313000  314500
  2971 2022-08-17   21906  314500  318000  309000  311000

  [2972 rows x 6 columns]},
 'Non_Metal': {'003670':              일자      거래량      시가      고가      저가      종가
  0    2010-06-08    43936    7097    7135    6937    7078
  1    2010-06-09    53468    7078    7106    6900    6956
  2    2010-06-10    54074    7041    7050    6956    6956
  3    2010-06-11    77606    7031    7088    6871    6956
  4    2010-06-14    48128    7050    7050    6787    6862
  ...         ...      ...     ...     ...     ...     ...
  3005 2022-08-10   850820  153000  155500  150500  153000
  3006 2022-08-11  1641466  156500  164500  155000  160500
  3007 2022-08-12   683358  159500  162000  157500  160000
  3008 2022-08-16   558384  161500  163500  159500  162000
  3009 2022-08-17  1175183  161500  167000  157000  158500

  [3010 rows x 6 columns],
  '003410':              일자      거래량    시가    고가    저가    종가
  0    2010-06-08   313987  1159  1164  1133  1159
  1    2010-06-09   333429  1159  1159  1131  1138
  2    2010-06-10  1011509  1133  1133  1094  1094
  3    2010-06-11   786857  1112  1118  1092  1094
  4    2010-06-14   643862  1105  1140  1099  1127
  ...         ...      ...   ...   ...   ...   ...
  3005 2022-08-10   361107  6850  6880  6760  6850
  3006 2022-08-11   367501  6860  6950  6850  6950
  3007 2022-08-12   355902  6950  7030  6920  7020
  3008 2022-08-16   548435  7030  7120  7020  7050
  3009 2022-08-17   414294  7120  7160  7030  7030

  [3010 rows x 6 columns],
  '010780':              일자     거래량     시가     고가     저가     종가
  0    2010-06-08   54032   5859   6191   5859   6153
  1    2010-06-09  109726   6217   6396   6185   6319
  2    2010-06-10  119332   6249   6908   6249   6844
  3    2010-06-11  101470   7004   7355   6588   6844
  4    2010-06-14   45652   7036   7036   6588   6620
  ...         ...     ...    ...    ...    ...    ...
  3005 2022-08-10  135944  40800  42000  40800  41700
  3006 2022-08-11   89958  42350  42350  40750  41300
  3007 2022-08-12   77121  41300  42500  41300  42500
  3008 2022-08-16   71228  42600  42900  41100  41400
  3009 2022-08-17  113084  41700  41750  40950  41200

  [3010 rows x 6 columns]},
 'Metal': {'005490':              일자     거래량      시가      고가      저가      종가
  0    2010-06-08  168069  447000  453000  442500  450000
  1    2010-06-09  269627  446000  452000  443000  447000
  2    2010-06-10  284195  450000  455000  445000  448500
  3    2010-06-11  341722  457500  466000  457000  465500
  4    2010-06-14  338840  474000  478500  470000  473000
  ...         ...     ...     ...     ...     ...     ...
  3005 2022-08-10  312580  247500  251500  246000  248500
  3006 2022-08-11  378261  251500  258000  250000  257000
  3007 2022-08-12  304190  257000  261500  255500  259500
  3008 2022-08-16  368851  263500  266500  257000  258000
  3009 2022-08-17  345178  260000  265500  257500  258000

  [3010 rows x 6 columns],
  '010130':              일자     거래량      시가      고가      저가      종가
  0    2010-06-08  150151  183000  187000  180000  183500
  1    2010-06-09  188979  187500  193000  186000  191000
  2    2010-06-10  150810  193000  198000  191500  198000
  3    2010-06-11   89388  198000  200500  195500  199500
  4    2010-06-14   85989  198000  205000  197000  203000
  ...         ...     ...     ...     ...     ...     ...
  3005 2022-08-10   55920  564000  571000  554000  563000
  3006 2022-08-11   95491  565000  589000  561000  586000
  3007 2022-08-12   53603  579000  600000  579000  588000
  3008 2022-08-16   45446  589000  607000  585000  596000
  3009 2022-08-17   65662  600000  619000  590000  597000

  [3010 rows x 6 columns],
  '004020':              일자     거래량     시가     고가     저가     종가
  0    2010-06-08  591502  82800  84300  82400  83000
  1    2010-06-09  694504  83800  85600  83100  85300
  2    2010-06-10  405120  85500  86800  84400  86500
  3    2010-06-11  499714  87500  87900  86700  87200
  4    2010-06-14  470386  87000  88800  87000  87800
  ...         ...     ...    ...    ...    ...    ...
  3005 2022-08-10  444027  33650  34200  33300  34000
  3006 2022-08-11  527339  34400  34700  34000  34600
  3007 2022-08-12  468719  34400  35200  34350  35100
  3008 2022-08-16  832719  35500  35800  33950  34050
  3009 2022-08-17  421305  34300  34500  33650  33900

  [3010 rows x 6 columns],
  '016380':              일자      거래량      시가      고가      저가      종가
  0    2010-06-08     2938  480258  491998  476523  491998
  1    2010-06-09     2197  494132  494132  482926  483460
  2    2010-06-10     2694  483993  498401  483993  493599
  3    2010-06-11     5667  501603  514943  498935  510674
  4    2010-06-14     7293  515477  533620  513876  532553
  ...         ...      ...     ...     ...     ...     ...
  3005 2022-08-10  1558036   12250   13350   12150   12500
  3006 2022-08-11   588713   12650   12850   12550   12750
  3007 2022-08-12   619172   12800   13000   12550   12750
  3008 2022-08-16  1451195   13050   13450   12900   12900
  3009 2022-08-17   549070   12900   13050   12600   12600

  [3010 rows x 6 columns],
  '001230':              일자     거래량     시가     고가     저가     종가
  0    2010-06-08  204919  18066  18382  17840  18382
  1    2010-06-09  211957  18382  18518  18111  18201
  2    2010-06-10  299575  18292  18969  18247  18653
  3    2010-06-11  241281  18924  19240  18924  19060
  4    2010-06-14  266388  19285  19692  19240  19556
  ...         ...     ...    ...    ...    ...    ...
  3005 2022-08-10  942778  13500  14250  13350  13900
  3006 2022-08-11  699825  14200  14350  13900  14050
  3007 2022-08-12  483674  13900  14250  13800  14200
  3008 2022-08-16  984637  14750  14900  14050  14100
  3009 2022-08-17  469996  14150  14400  13800  13800

  [3010 rows x 6 columns]},
 'Machine': {'034020':              일자       거래량     시가     고가     저가     종가
  0    2010-06-08    733424  53244  54009  52709  53780
  1    2010-06-09   1401169  53780  56228  53015  53627
  2    2010-06-10    611957  54392  55233  54162  54468
  3    2010-06-11    602592  55463  55463  54545  54927
  4    2010-06-14    552733  55310  55845  54851  55310
  ...         ...       ...    ...    ...    ...    ...
  3005 2022-08-10   9019644  19800  20500  19600  20200
  3006 2022-08-11   5736690  20500  20650  20100  20300
  3007 2022-08-12  14352395  20400  21700  20350  21150
  3008 2022-08-16   8389809  21250  21800  20850  21200
  3009 2022-08-17   6262870  21200  21700  21100  21200

  [3010 rows x 6 columns],
  '018880':              일자      거래량     시가     고가     저가     종가
  0    2010-06-08  1276965   3000   3090   2970   3050
  1    2010-06-09  1323250   3070   3090   3010   3080
  2    2010-06-10  2192070   3080   3130   2990   3050
  3    2010-06-11   833625   3100   3100   3020   3020
  4    2010-06-14  1119085   3040   3170   3040   3140
  ...         ...      ...    ...    ...    ...    ...
  3005 2022-08-10   503040  11250  11250  10800  10850
  3006 2022-08-11   595513  11000  11200  10900  11000
  3007 2022-08-12   615798  10900  11100  10700  10800
  3008 2022-08-16   497793  10950  10950  10600  10750

In [ ]:
df_sector_UTD['Food']['097950'].iloc[2999:3007]

In [17]:
with open('df_sector_UTD.pickle','wb') as f:
    pickle.dump(df_sector_UTD,f)